import { useSearchParams } from "wouter";

export default function CardPreview() {
  // Grab the player name from the URL (?name=Gareth%20Bale)
  const searchParams = new URLSearchParams(window.location.search);
  const playerName = searchParams.get("name") || "Player Build";

  return (
    <div style={{ background: "#09090b", minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", padding: "16px" }}>
      {/* 
        👉 IMPORTANT: This ID must match '#final-player-card' 
        so Puppeteer knows exactly what box to screenshot!
      */}
      <div 
        id="final-player-card" 
        style={{ 
          width: "400px", 
          borderRadius: "16px", 
          background: "linear-gradient(135deg, #18181b 0%, #09090b 100%)", 
          border: "2px solid #27272a", 
          padding: "24px", 
          color: "#fff", 
          boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.5)" 
        }}
      >
        <div style={{ textAlign: "center", marginBottom: "16px" }}>
          <span style={{ fontSize: "12px", textTransform: "uppercase", tracking: "2px", color: "#a1a1aa", fontWeight: "bold" }}>
            ClubsDNA Meta Build
          </span>
          <h1 style={{ fontSize: "28px", fontWeight: "900", margin: "4px 0 0 0", color: "#38bdf8" }}>
            {playerName}
          </h1>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px", background: "#18181b", padding: "16px", borderRadius: "12px", border: "1fr solid #27272a" }}>
          <div>
            <div style={{ fontSize: "12px", color: "#71717a" }}>Pace</div>
            <div style={{ fontSize: "20px", fontWeight: "bold" }}>94</div>
          </div>
          <div>
            <div style={{ fontSize: "12px", color: "#71717a" }}>Shooting</div>
            <div style={{ fontSize: "20px", fontWeight: "bold" }}>88</div>
          </div>
          <div>
            <div style={{ fontSize: "12px", color: "#71717a" }}>Passing</div>
            <div style={{ fontSize: "20px", fontWeight: "bold" }}>85</div>
          </div>
          <div>
            <div style={{ fontSize: "12px", color: "#71717a" }}>Dribbling</div>
            <div style={{ fontSize: "20px", fontWeight: "bold" }}>91</div>
          </div>
        </div>

        <div style={{ marginTop: "16px", textAlign: "center", fontSize: "12px", color: "#52525b" }}>
          Generated by baller-engine.onrender.com
        </div>
      </div>
    </div>
  );
}
